'use client'

import { useState, useRef, useCallback } from 'react'
import Link from 'next/link'
import { useAppStore } from '@/stores/app-store'
import { T } from '@/lib/i18n/translations'
import type { DetectionResult } from '@/types/database'

type DetectTab = 'text' | 'image' | 'audio'

const TABS: { key: DetectTab; label: string; icon: string }[] = [
  { key: 'text', label: 'Text', icon: 'T' },
  { key: 'image', label: 'Image', icon: 'I' },
  { key: 'audio', label: 'Audio', icon: 'A' },
]

export default function DetectionPage() {
  const { lang } = useAppStore()
  const t = T[lang]

  const [tab, setTab] = useState<DetectTab>('text')
  const [textInput, setTextInput] = useState('')
  const [imageFile, setImageFile] = useState<File | null>(null)
  const [audioFile, setAudioFile] = useState<File | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [history, setHistory] = useState<DetectionResult[]>([])
  const [dragOver, setDragOver] = useState(false)
  const imageInputRef = useRef<HTMLInputElement>(null)
  const audioInputRef = useRef<HTMLInputElement>(null)

  const handleDetect = useCallback(async () => {
    setLoading(true)
    setError(null)

    try {
      let res: Response

      if (tab === 'text') {
        if (!textInput.trim()) return
        res = await fetch('/api/v1/detect/text', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ text: textInput }),
        })
      } else if (tab === 'image') {
        if (!imageFile) return
        const formData = new FormData()
        formData.append('file', imageFile)
        res = await fetch('/api/v1/detect/image', { method: 'POST', body: formData })
      } else {
        if (!audioFile) return
        const formData = new FormData()
        formData.append('file', audioFile)
        res = await fetch('/api/v1/detect/audio', { method: 'POST', body: formData })
      }

      if (!res.ok) throw new Error('Detection failed')
      const data: DetectionResult = await res.json()
      setHistory((prev) => [data, ...prev])
      setTextInput('')
      setImageFile(null)
      setAudioFile(null)
    } catch {
      setError('Detection failed. Please try again.')
    } finally {
      setLoading(false)
    }
  }, [tab, textInput, imageFile, audioFile])

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault()
      setDragOver(false)
      const file = e.dataTransfer.files[0]
      if (!file) return
      if (tab === 'image') setImageFile(file)
      if (tab === 'audio') setAudioFile(file)
    },
    [tab]
  )

  const canDetect =
    (tab === 'text' && textInput.trim().length > 0) ||
    (tab === 'image' && imageFile !== null) ||
    (tab === 'audio' && audioFile !== null)

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-semibold text-foreground">{t.detection}</h1>
        <p className="text-sm text-muted-foreground mt-1">
          Detect AI-generated content across text, images, and audio.
        </p>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 bg-muted rounded-xl p-1">
        {TABS.map((tb) => (
          <button
            key={tb.key}
            onClick={() => {
              setTab(tb.key)
              setError(null)
            }}
            className={`flex-1 flex items-center justify-center gap-2 py-2.5 rounded-lg text-sm font-medium transition-all ${
              tab === tb.key
                ? 'bg-card text-foreground shadow-sm'
                : 'text-muted-foreground hover:text-foreground'
            }`}
          >
            <span className="w-6 h-6 rounded bg-primary/10 text-primary text-xs flex items-center justify-center font-bold">
              {tb.icon}
            </span>
            {tb.label}
          </button>
        ))}
      </div>

      {/* Input area */}
      <div className="bg-card border border-border rounded-xl p-6 space-y-4">
        {tab === 'text' && (
          <textarea
            value={textInput}
            onChange={(e) => setTextInput(e.target.value)}
            placeholder="Paste text here to check if it was generated by AI..."
            rows={6}
            className="w-full bg-muted border border-border rounded-lg px-4 py-3 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary resize-none"
          />
        )}

        {tab === 'image' && (
          <div
            onDragOver={(e) => { e.preventDefault(); setDragOver(true) }}
            onDragLeave={() => setDragOver(false)}
            onDrop={handleDrop}
            onClick={() => imageInputRef.current?.click()}
            className={`border-2 border-dashed rounded-xl p-10 text-center cursor-pointer transition-colors ${
              dragOver ? 'border-primary bg-primary/5' : imageFile ? 'border-emerald-500/50 bg-emerald-500/5' : 'border-border hover:border-primary/40'
            }`}
          >
            <input
              ref={imageInputRef}
              type="file"
              accept="image/*"
              className="hidden"
              onChange={(e) => setImageFile(e.target.files?.[0] ?? null)}
            />
            {imageFile ? (
              <div className="space-y-1">
                <p className="text-sm text-foreground font-medium">{imageFile.name}</p>
                <p className="text-xs text-muted-foreground">{(imageFile.size / 1024).toFixed(1)} KB</p>
              </div>
            ) : (
              <div className="space-y-2">
                <div className="w-10 h-10 rounded-xl bg-muted flex items-center justify-center mx-auto">
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-muted-foreground">
                    <rect x="3" y="3" width="18" height="18" rx="2" />
                    <circle cx="8.5" cy="8.5" r="1.5" />
                    <path d="M21 15l-5-5L5 21" />
                  </svg>
                </div>
                <p className="text-sm text-muted-foreground">Drop an image or <span className="text-primary">browse</span></p>
              </div>
            )}
          </div>
        )}

        {tab === 'audio' && (
          <div
            onDragOver={(e) => { e.preventDefault(); setDragOver(true) }}
            onDragLeave={() => setDragOver(false)}
            onDrop={handleDrop}
            onClick={() => audioInputRef.current?.click()}
            className={`border-2 border-dashed rounded-xl p-10 text-center cursor-pointer transition-colors ${
              dragOver ? 'border-primary bg-primary/5' : audioFile ? 'border-emerald-500/50 bg-emerald-500/5' : 'border-border hover:border-primary/40'
            }`}
          >
            <input
              ref={audioInputRef}
              type="file"
              accept="audio/*"
              className="hidden"
              onChange={(e) => setAudioFile(e.target.files?.[0] ?? null)}
            />
            {audioFile ? (
              <div className="space-y-1">
                <p className="text-sm text-foreground font-medium">{audioFile.name}</p>
                <p className="text-xs text-muted-foreground">{(audioFile.size / 1024).toFixed(1)} KB</p>
              </div>
            ) : (
              <div className="space-y-2">
                <div className="w-10 h-10 rounded-xl bg-muted flex items-center justify-center mx-auto">
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-muted-foreground">
                    <path d="M9 18V5l12-2v13" />
                    <circle cx="6" cy="18" r="3" />
                    <circle cx="18" cy="16" r="3" />
                  </svg>
                </div>
                <p className="text-sm text-muted-foreground">Drop an audio file or <span className="text-primary">browse</span></p>
              </div>
            )}
          </div>
        )}

        <button
          onClick={handleDetect}
          disabled={!canDetect || loading}
          className="w-full py-3 bg-primary text-primary-foreground text-sm font-semibold rounded-lg hover:bg-primary/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
        >
          {loading ? (
            <>
              <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24" fill="none">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.4 0 0 5.4 0 12h4z" />
              </svg>
              Analyzing...
            </>
          ) : (
            'Detect AI Content'
          )}
        </button>

        {error && (
          <div className="bg-red-500/10 border border-red-500/20 rounded-lg p-3">
            <p className="text-sm text-red-400">{error}</p>
          </div>
        )}
      </div>

      {/* Detection History */}
      <div>
        <h2 className="text-lg font-semibold text-foreground mb-4">Detection History</h2>
        {history.length === 0 ? (
          <div className="bg-card border border-border rounded-xl p-8 text-center">
            <p className="text-sm text-muted-foreground">{t.noResults}</p>
          </div>
        ) : (
          <div className="bg-card border border-border rounded-xl overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-border text-left">
                    <th className="px-4 py-3 font-medium text-muted-foreground">Input Type</th>
                    <th className="px-4 py-3 font-medium text-muted-foreground">Result</th>
                    <th className="px-4 py-3 font-medium text-muted-foreground">Confidence</th>
                    <th className="px-4 py-3 font-medium text-muted-foreground">Provider</th>
                    <th className="px-4 py-3 font-medium text-muted-foreground">Date</th>
                  </tr>
                </thead>
                <tbody>
                  {history.map((item) => (
                    <tr key={item.id} className="border-b border-border last:border-0 hover:bg-muted/50 transition-colors">
                      <td className="px-4 py-3">
                        <span className="inline-flex px-2 py-0.5 rounded-full text-xs font-medium bg-primary/10 text-primary capitalize">
                          {item.content_type}
                        </span>
                      </td>
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-2">
                          <div className={`w-2 h-2 rounded-full ${item.is_ai_generated ? 'bg-amber-400' : 'bg-emerald-400'}`} />
                          <span className="text-foreground text-xs">
                            {item.is_ai_generated === null ? 'Inconclusive' : item.is_ai_generated ? 'AI Generated' : 'Human'}
                          </span>
                        </div>
                      </td>
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-2">
                          <div className="w-16 h-1.5 rounded-full bg-muted overflow-hidden">
                            <div
                              className="h-full rounded-full bg-primary"
                              style={{ width: `${item.confidence ?? 0}%` }}
                            />
                          </div>
                          <span className="text-xs text-muted-foreground">{item.confidence ?? 0}%</span>
                        </div>
                      </td>
                      <td className="px-4 py-3 text-foreground text-xs">
                        {item.provider_detected || '--'}
                      </td>
                      <td className="px-4 py-3 text-muted-foreground text-xs">
                        {new Date(item.created_at).toLocaleString()}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
