/**
 * C2PA (Coalition for Content Provenance and Authenticity) manifest generation.
 * Generates simplified C2PA-compatible JSON manifests for AI-generated content.
 *
 * Reference: https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html
 */

export interface C2PAManifestOptions {
  contentHash: string;
  provider: string;
  model: string;
  generationDate: string;
  watermarkId: string;
  issuer: string;
}

export interface C2PAAssertion {
  label: string;
  data: Record<string, unknown>;
}

export interface C2PAManifest {
  claim_generator: string;
  title: string;
  format: string;
  instance_id: string;
  assertions: C2PAAssertion[];
  signature_info: {
    issuer: string;
    time: string;
    alg: string;
  };
}

/**
 * Generate a C2PA-compatible manifest JSON structure.
 *
 * Includes assertions for:
 * - c2pa.created: creation action with AI generation details
 * - c2pa.hash.data: content hash for integrity verification
 * - stds.schema-org.CreativeWork: schema.org metadata marking as AI-generated
 */
export function generateC2PAManifest(options: C2PAManifestOptions): C2PAManifest {
  const {
    contentHash,
    provider,
    model,
    generationDate,
    watermarkId,
    issuer,
  } = options;

  const instanceId = `urn:markify:${watermarkId}`;

  return {
    claim_generator: 'Markify/1.0',
    title: `AI-Generated Content — ${watermarkId}`,
    format: 'application/octet-stream',
    instance_id: instanceId,
    assertions: [
      {
        label: 'c2pa.actions',
        data: {
          actions: [
            {
              action: 'c2pa.created',
              softwareAgent: `${provider}/${model}`,
              when: generationDate,
              parameters: {
                description: 'Content generated by AI',
                ai: {
                  provider,
                  model,
                  type: 'generative',
                },
              },
            },
          ],
        },
      },
      {
        label: 'c2pa.hash.data',
        data: {
          exclusions: [],
          name: 'sha256',
          hash: contentHash,
          pad: '',
        },
      },
      {
        label: 'stds.schema-org.CreativeWork',
        data: {
          '@context': 'https://schema.org',
          '@type': 'CreativeWork',
          author: {
            '@type': 'Organization',
            name: provider,
          },
          encodingFormat: 'application/octet-stream',
          abstract: `Generated by ${model} (${provider})`,
          dateCreated: generationDate,
          identifier: watermarkId,
          creditText: `AI-generated content by ${provider} ${model}`,
          copyrightNotice: `Content generated by AI (${provider} ${model}). Watermark ID: ${watermarkId}`,
        },
      },
      {
        label: 'c2pa.training-mining',
        data: {
          entries: [
            {
              use: 'notAllowed',
              constraint_info:
                'This AI-generated content is watermarked and tracked by Markify.',
            },
          ],
        },
      },
    ],
    signature_info: {
      issuer,
      time: generationDate,
      alg: 'RS256',
    },
  };
}
