'use client'

import { useState, useRef, useCallback } from 'react'
import Link from 'next/link'

type DetectTab = 'text' | 'image' | 'audio'

interface DetectionResult {
  is_ai_generated: boolean | null
  confidence: number | null
  provider_detected: string | null
  model_detected: string | null
  reasoning: string | null
  watermark_found: boolean
  watermark_id: string | null
}

const TABS: { key: DetectTab; label: string; icon: string }[] = [
  { key: 'text', label: 'Text', icon: 'T' },
  { key: 'image', label: 'Image', icon: 'I' },
  { key: 'audio', label: 'Audio', icon: 'A' },
]

export default function PublicDetectPage() {
  const [tab, setTab] = useState<DetectTab>('text')
  const [textInput, setTextInput] = useState('')
  const [imageFile, setImageFile] = useState<File | null>(null)
  const [audioFile, setAudioFile] = useState<File | null>(null)
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState<DetectionResult | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [detectionsUsed, setDetectionsUsed] = useState(0)
  const imageInputRef = useRef<HTMLInputElement>(null)
  const audioInputRef = useRef<HTMLInputElement>(null)
  const [dragOver, setDragOver] = useState(false)

  const MAX_FREE = 10

  const handleDetect = useCallback(async () => {
    if (detectionsUsed >= MAX_FREE) return
    setLoading(true)
    setResult(null)
    setError(null)

    try {
      let res: Response

      if (tab === 'text') {
        if (!textInput.trim()) return
        res = await fetch('/api/v1/detect/text', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ text: textInput }),
        })
      } else if (tab === 'image') {
        if (!imageFile) return
        const formData = new FormData()
        formData.append('file', imageFile)
        res = await fetch('/api/v1/detect/image', {
          method: 'POST',
          body: formData,
        })
      } else {
        if (!audioFile) return
        const formData = new FormData()
        formData.append('file', audioFile)
        res = await fetch('/api/v1/detect/audio', {
          method: 'POST',
          body: formData,
        })
      }

      if (!res.ok) throw new Error('Detection failed')
      const data = await res.json()
      setResult(data)
      setDetectionsUsed((prev) => prev + 1)
    } catch {
      setError('Detection failed. Please try again.')
    } finally {
      setLoading(false)
    }
  }, [tab, textInput, imageFile, audioFile, detectionsUsed])

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault()
      setDragOver(false)
      const file = e.dataTransfer.files[0]
      if (!file) return
      if (tab === 'image') setImageFile(file)
      if (tab === 'audio') setAudioFile(file)
    },
    [tab]
  )

  const canDetect =
    (tab === 'text' && textInput.trim().length > 0) ||
    (tab === 'image' && imageFile !== null) ||
    (tab === 'audio' && audioFile !== null)

  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Header */}
      <header className="border-b border-border bg-card/50">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="text-xl font-bold text-foreground">
            <span className="text-primary">Mark</span>ify
          </Link>
          <span className="text-sm text-muted-foreground">AI Detection Playground</span>
        </div>
      </header>

      <main className="flex-1 max-w-3xl mx-auto w-full px-6 py-10 space-y-6">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-foreground">AI Content Detection</h1>
          <p className="text-muted-foreground text-sm mt-2">
            Check if content was generated by AI. Supports text, images, and audio.
          </p>
        </div>

        {/* Rate limit notice */}
        <div className="bg-card border border-border rounded-xl p-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center text-primary text-sm font-bold">
              {MAX_FREE - detectionsUsed}
            </div>
            <span className="text-sm text-muted-foreground">
              {detectionsUsed >= MAX_FREE
                ? 'Daily limit reached.'
                : `${MAX_FREE - detectionsUsed} free detections remaining today.`}
            </span>
          </div>
          <Link
            href="/register"
            className="text-sm text-primary font-medium hover:text-primary/80 transition-colors"
          >
            Sign up for unlimited
          </Link>
        </div>

        {/* Tabs */}
        <div className="flex gap-1 bg-muted rounded-xl p-1">
          {TABS.map((t) => (
            <button
              key={t.key}
              onClick={() => {
                setTab(t.key)
                setResult(null)
                setError(null)
              }}
              className={`flex-1 flex items-center justify-center gap-2 py-2.5 rounded-lg text-sm font-medium transition-all ${
                tab === t.key
                  ? 'bg-card text-foreground shadow-sm'
                  : 'text-muted-foreground hover:text-foreground'
              }`}
            >
              <span className="w-6 h-6 rounded bg-primary/10 text-primary text-xs flex items-center justify-center font-bold">
                {t.icon}
              </span>
              {t.label}
            </button>
          ))}
        </div>

        {/* Input area */}
        <div className="bg-card border border-border rounded-xl p-6 space-y-4">
          {tab === 'text' && (
            <textarea
              value={textInput}
              onChange={(e) => setTextInput(e.target.value)}
              placeholder="Paste text here to check if it was generated by AI..."
              rows={8}
              className="w-full bg-muted border border-border rounded-lg px-4 py-3 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary resize-none"
            />
          )}

          {tab === 'image' && (
            <div
              onDragOver={(e) => {
                e.preventDefault()
                setDragOver(true)
              }}
              onDragLeave={() => setDragOver(false)}
              onDrop={handleDrop}
              onClick={() => imageInputRef.current?.click()}
              className={`border-2 border-dashed rounded-xl p-12 text-center cursor-pointer transition-colors ${
                dragOver
                  ? 'border-primary bg-primary/5'
                  : imageFile
                  ? 'border-emerald-500/50 bg-emerald-500/5'
                  : 'border-border hover:border-primary/40'
              }`}
            >
              <input
                ref={imageInputRef}
                type="file"
                accept="image/*"
                className="hidden"
                onChange={(e) => setImageFile(e.target.files?.[0] ?? null)}
              />
              {imageFile ? (
                <div className="space-y-2">
                  <div className="w-12 h-12 rounded-xl bg-emerald-500/10 flex items-center justify-center mx-auto">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-emerald-400">
                      <polyline points="20 6 9 17 4 12" />
                    </svg>
                  </div>
                  <p className="text-sm text-foreground font-medium">{imageFile.name}</p>
                  <p className="text-xs text-muted-foreground">
                    {(imageFile.size / 1024).toFixed(1)} KB
                  </p>
                </div>
              ) : (
                <div className="space-y-2">
                  <div className="w-12 h-12 rounded-xl bg-muted flex items-center justify-center mx-auto">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-muted-foreground">
                      <rect x="3" y="3" width="18" height="18" rx="2" />
                      <circle cx="8.5" cy="8.5" r="1.5" />
                      <path d="M21 15l-5-5L5 21" />
                    </svg>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Drop an image here or <span className="text-primary">browse</span>
                  </p>
                  <p className="text-xs text-muted-foreground">PNG, JPG, WebP up to 10MB</p>
                </div>
              )}
            </div>
          )}

          {tab === 'audio' && (
            <div
              onDragOver={(e) => {
                e.preventDefault()
                setDragOver(true)
              }}
              onDragLeave={() => setDragOver(false)}
              onDrop={handleDrop}
              onClick={() => audioInputRef.current?.click()}
              className={`border-2 border-dashed rounded-xl p-12 text-center cursor-pointer transition-colors ${
                dragOver
                  ? 'border-primary bg-primary/5'
                  : audioFile
                  ? 'border-emerald-500/50 bg-emerald-500/5'
                  : 'border-border hover:border-primary/40'
              }`}
            >
              <input
                ref={audioInputRef}
                type="file"
                accept="audio/*"
                className="hidden"
                onChange={(e) => setAudioFile(e.target.files?.[0] ?? null)}
              />
              {audioFile ? (
                <div className="space-y-2">
                  <div className="w-12 h-12 rounded-xl bg-emerald-500/10 flex items-center justify-center mx-auto">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-emerald-400">
                      <polyline points="20 6 9 17 4 12" />
                    </svg>
                  </div>
                  <p className="text-sm text-foreground font-medium">{audioFile.name}</p>
                  <p className="text-xs text-muted-foreground">
                    {(audioFile.size / 1024).toFixed(1)} KB
                  </p>
                </div>
              ) : (
                <div className="space-y-2">
                  <div className="w-12 h-12 rounded-xl bg-muted flex items-center justify-center mx-auto">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-muted-foreground">
                      <path d="M9 18V5l12-2v13" />
                      <circle cx="6" cy="18" r="3" />
                      <circle cx="18" cy="16" r="3" />
                    </svg>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Drop an audio file here or <span className="text-primary">browse</span>
                  </p>
                  <p className="text-xs text-muted-foreground">MP3, WAV, OGG up to 25MB</p>
                </div>
              )}
            </div>
          )}

          <button
            onClick={handleDetect}
            disabled={!canDetect || loading || detectionsUsed >= MAX_FREE}
            className="w-full py-3 bg-primary text-primary-foreground text-sm font-semibold rounded-lg hover:bg-primary/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          >
            {loading ? (
              <>
                <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24" fill="none">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.4 0 0 5.4 0 12h4z" />
                </svg>
                Analyzing...
              </>
            ) : (
              'Detect AI Content'
            )}
          </button>
        </div>

        {/* Error */}
        {error && (
          <div className="bg-red-500/10 border border-red-500/20 rounded-xl p-4">
            <p className="text-sm text-red-400">{error}</p>
          </div>
        )}

        {/* Result */}
        {result && (
          <div className="bg-card border border-border rounded-xl overflow-hidden">
            <div className="px-6 py-4 border-b border-border">
              <h3 className="text-sm font-semibold text-foreground uppercase tracking-wider">Detection Result</h3>
            </div>
            <div className="p-6 space-y-5">
              {/* Confidence meter */}
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm text-muted-foreground">AI Confidence</span>
                  <span className="text-sm font-bold text-foreground">
                    {result.confidence !== null ? `${result.confidence}%` : 'N/A'}
                  </span>
                </div>
                <div className="h-3 rounded-full bg-muted overflow-hidden">
                  <div
                    className="h-full rounded-full transition-all duration-700"
                    style={{
                      width: `${result.confidence ?? 0}%`,
                      background: `linear-gradient(90deg, #10b981 0%, #f59e0b 50%, #ef4444 100%)`,
                    }}
                  />
                </div>
                <div className="flex justify-between mt-1">
                  <span className="text-xs text-muted-foreground">Human</span>
                  <span className="text-xs text-muted-foreground">AI Generated</span>
                </div>
              </div>

              {/* Verdict */}
              <div className="flex items-center gap-3 p-4 rounded-lg bg-muted">
                <div
                  className={`w-3 h-3 rounded-full ${
                    result.is_ai_generated ? 'bg-amber-400' : 'bg-emerald-400'
                  }`}
                />
                <span className="text-sm font-medium text-foreground">
                  {result.is_ai_generated === null
                    ? 'Inconclusive'
                    : result.is_ai_generated
                    ? 'Likely AI-Generated'
                    : 'Likely Human-Created'}
                </span>
              </div>

              {/* Details */}
              <div className="space-y-3">
                {result.provider_detected && (
                  <div className="flex justify-between">
                    <span className="text-sm text-muted-foreground">Provider Guess</span>
                    <span className="text-sm text-foreground font-medium">{result.provider_detected}</span>
                  </div>
                )}
                {result.model_detected && (
                  <div className="flex justify-between">
                    <span className="text-sm text-muted-foreground">Model Guess</span>
                    <span className="text-sm text-foreground font-medium">{result.model_detected}</span>
                  </div>
                )}
                {result.watermark_found && (
                  <div className="flex justify-between">
                    <span className="text-sm text-muted-foreground">Watermark</span>
                    <Link
                      href={`/verify/${result.watermark_id}`}
                      className="text-sm text-primary font-medium hover:text-primary/80"
                    >
                      Found - Verify
                    </Link>
                  </div>
                )}
                {result.reasoning && (
                  <div className="pt-3 border-t border-border">
                    <p className="text-sm text-muted-foreground leading-relaxed">{result.reasoning}</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-border py-6 text-center">
        <Link href="/" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
          Powered by <span className="text-primary font-medium">Markify</span>
        </Link>
      </footer>
    </div>
  )
}
