/**
 * AI content detection using the Claude API.
 * Analyzes text for patterns indicative of AI-generated content.
 */

import Anthropic from '@anthropic-ai/sdk';

export interface TextDetectionResult {
  isAIGenerated: boolean;
  confidence: number;
  reasoning: string;
  providerGuess: string | null;
  modelGuess: string | null;
}

const DETECTION_PROMPT = `You are an expert AI content detection system. Analyze the following text and determine whether it was likely generated by an AI language model or written by a human.

Evaluate these dimensions:
1. **Linguistic patterns**: AI text tends to use hedging phrases ("It's important to note", "However"), formulaic transitions, and balanced sentence structure. Human text is more variable and idiosyncratic.
2. **Vocabulary diversity**: AI models tend toward a predictable vocabulary distribution. Look for overuse of words like "delve", "tapestry", "multifaceted", "nuanced", "crucial", "landscape".
3. **Structural patterns**: AI text often follows predictable structures (intro, list of points, conclusion). Human text is more organic.
4. **Creativity and voice**: Human text shows personality quirks, humor, colloquialisms, and unexpected turns. AI text tends to be more uniform in tone.
5. **Factual hedging**: AI models often add unnecessary caveats and qualifications.
6. **Repetition patterns**: Look for semantic repetition where the same idea is restated in slightly different ways.

Respond with a JSON object (no markdown, no code fences) with these exact fields:
{
  "isAIGenerated": boolean,
  "confidence": number between 0.0 and 1.0,
  "reasoning": "brief explanation of key indicators found",
  "providerGuess": "OpenAI" | "Anthropic" | "Google" | "Meta" | null,
  "modelGuess": "specific model name guess" | null
}

Text to analyze:
"""
{TEXT}
"""`;

/**
 * Detect whether text is AI-generated using Claude API analysis.
 * Returns confidence score, reasoning, and provider/model guesses.
 */
export async function detectAIText(text: string): Promise<TextDetectionResult> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    throw new Error('ANTHROPIC_API_KEY environment variable is not set');
  }

  const client = new Anthropic({ apiKey });

  const prompt = DETECTION_PROMPT.replace('{TEXT}', text);

  const response = await client.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 1024,
    messages: [
      {
        role: 'user',
        content: prompt,
      },
    ],
  });

  // Extract the text content from the response
  const content = response.content[0];
  if (content.type !== 'text') {
    throw new Error('Unexpected response type from Claude API');
  }

  try {
    const result = JSON.parse(content.text) as TextDetectionResult;

    // Validate and clamp confidence
    return {
      isAIGenerated: Boolean(result.isAIGenerated),
      confidence: Math.max(0, Math.min(1, Number(result.confidence) || 0)),
      reasoning: String(result.reasoning || 'No reasoning provided'),
      providerGuess: result.providerGuess ?? null,
      modelGuess: result.modelGuess ?? null,
    };
  } catch {
    // If JSON parsing fails, return a fallback result
    return {
      isAIGenerated: false,
      confidence: 0,
      reasoning: `Failed to parse detection response: ${content.text.slice(0, 200)}`,
      providerGuess: null,
      modelGuess: null,
    };
  }
}
